: DBG-TOKEN DUP DUP 0x7F > SWAP 0xFD < AND IF DEBUG-HELP 9 + c! DEBUG-HELP EXEC ELSE DROP ;
: DBG-NUMBER DUP C@ 0XFF = IF 1+ @ $. ELSE DROP THEN ;
: DBG-STRING DUP C@ 0xFE = NOT IF DROP ELSE BEGIN 1+ DUP C@ DUP DUP IF EMIT ELSE DROP THEN NOT UNTIL 0x20 EMIT DROP THEN ;
: DBG-HOOK  '|' EMIT  DUP C@ DUP $. DUP DUP 0x7F > SWAP 0xFD < AND  IF .TOK ELSE DROP DUP DBG-STRING DBG-NUMBER CR THEN ;
: DBG-ON 0x80 OPT ! ;
: DBG-OFF 0x40 OPT ! ;


