: SWITCH 0#4  INP ;
: LEDS 0#4  SWAP OUT ;
: SCANLEFT 0#8  0#0  DO 0#1  I LSHIFT LEDSHOW LOOP ;
: SCANRIGHT 0#8  0#0  DO 0#128  I RSHIFT LEDSHOW LOOP ;
: LEDSHOW LEDS SWITCH 1+ DELAY ;                         
: SCAN SWITCH WHILE SCANLEFT SCANRIGHT SWITCH REPEAT ;

